### ISSUE TITLE
Typo 'Domain-Driver Design' should be 'Domain-Driven Design' in manuscript-en/06-names.md.

### ISSUE THREAD

**Issue by rouilj** [bespoyasov/refactor-like-a-superhero#1]
See:

https://github.com/bespoyasov/refactor-like-a-superhero-online-book/blob/main/manuscript-en/06-names.md?plain=1#L206

**Comment by bespoyasov** [comment]
Thanks for spotting!

Fixed: https://github.com/bespoyasov/refactor-like-a-superhero-online-book/commit/e06d589b630300ba322c92c5ac19f1492df29dfd
