### ISSUE TITLE
Generate PDF and Epub versions

### ISSUE THREAD

**Issue by mindyourlifeguide** [bespoyasov/refactor-like-a-superhero#46]
epub version
[Riefaktoringh na maksimalkakh - Alieksandr Biespoiasov.zip](https://github.com/bespoyasov/refactor-like-a-superhero/files/10104776/Riefaktoringh.na.maksimalkakh.-.Alieksandr.Biespoiasov.zip)

**Comment by mindyourlifeguide** [comment]
how to do it:
pandoc command and some calibre magic

`pandoc -o file.epub README.md TOC.md 01-preface.md 02-introduction.md 03-before-start.md 04-during-refactoring.md 05-low-hanging-fruit.md 06-names.md 07-duplication.md 08-abstraction.md 09-functional-pipeline.md 10-conditions.md 11-side-effects.md 12-error-handling.md 13-module-integration.md 14-generics.md 15-architecture.md 16-declarative-style.md 17-static-typing.md 18-test-code.md 19-comments-and-docs.md 20-refactoring-process.md 21-afterword.md 22-cheatsheet.md 23-sources.md`

**Comment by bespoyasov** [comment]
Hey!
Yeah, that's a great idea!

I'm now working on generating PDF when building the [web UI](https://refactor-like-a-superhero.vercel.app/en)). I suppose I can add Epub generation then as well.

I will update Readme when I will have done it :–)

**Comment by bespoyasov** [comment]
Added PDF and Epub generation to www, the ebook is now available by [this link](https://refactor-like-a-superhero.vercel.app/en#download-ebook) 👀
