### ISSUE TITLE
Возможная ошибка примера Законы де Моргана

### ISSUE THREAD

**Issue by VictorDanilov** [bespoyasov/refactor-like-a-superhero#52]
Когда пробую понять эти преобразования, возникает какое-то противоречие, как будто где-то ошибка.

[Глава](https://github.com/bespoyasov/refactor-like-a-superhero/blob/main/manuscript-ru/10-conditions.md#%D0%B7%D0%B0%D0%BA%D0%BE%D0%BD%D1%8B-%D0%B4%D0%B5-%D0%BC%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B0)

```
// Вынесем 2-е вложенное условие в переменную:
const hasAdvantage = hasHeavyArmor || hasResistance;

// Заметим, что по первому закону де Моргана
// 1-е вложенное условие превратится в !hasAdvantage:
//
// !A || !B === !(A && B)
//
// A -> hasHeavyArmor
// B -> hasResistance
//
// !hasHeavyArmor || !hasResistance
//    === !(hasHeavyArmor && hasResistance)
//    === !hasAdvantage

// Тогда всё условие станет выглядеть так:
if (hasHighScore && !hasAdvantage) {
} else if (!hasHighScore && hasAdvantage) {
}
```

Либо я неправильно применяю, но у меня в голове так должно быть:

`const hasAdvantage = hasHeavyArmor || hasResistance;`
накидываем отрицание на две стороны
`!hasAdvantage = !(hasHeavyArmor || hasResistance)`
по закону это так
`!(hasHeavyArmor || hasResistance) = !hasHeavyArmor && !hasResistance`

И глядя на то, что у тебя написано `!hasHeavyArmor || !hasResistance`, в
```
// !hasHeavyArmor || !hasResistance
//    === !(hasHeavyArmor && hasResistance)
//    === !hasAdvantage
```
вызывает вопросы:)

Но я даже [пример собрал](https://www.typescriptlang.org/play?#code/PTAEGMHsDsGcBdQFdYFMBOoC8oDeoRQAGAKENFFinVQC5QA2IgGjLAoEN0BbSdepq3KgasAJYIO0cHVABGNqAC+iqHEQoM2PATBF5iilT6zBh0F179GLc6InwpM+qUIrCahMjSYc+QvoKwsY0ArbClnz0AEzh7CKo4pLSskFg7mCeGj7a-mDR5iGyACxxFBY8UaAAzGUU9snOxIoZEDBemr46hNE1hdQldRVWMUMNjin0acqq7dlafrqgvdX9JvSlQvGR1mbC406yrukkJFneC916BkYDYayclbu29YkOhy4kKmdzoAAWHFgAAkxABzP4AZQG2k6ADoiqAAHw4ACsRAA3D91P9AUDUBwAG4ATwAgk8YT5YTskaiMVivADYAAlN6NVAUjCwg4pbBYHByTH0xCMkkAEwJUkcoPZOEZeMJpPJAB8lTjmayJjJBWIAGagAAUcrBkIGAEo8CQKJ5IAAbVCwm2QUH6oimy1LXUGgCEIvFko40vNuHdnv1Ptx+OJZKsoBVoHD6qSmtQQfdVvatvtjudcjdFBUSlAqBtaFAoYTIPBUJMqfTcEzDqd+uiebLesNgLFEugUpTFvKbXrdsbzuqrYLJCAA), и ```if (!hasAdvantage) {``` и ```if (!hasHeavyArmor || !hasResistance) {``` не взаимозаменяемыми выходят.

**Comment by bespoyasov** [comment]
Оу, спасибо за внимательность!

Да, там конечно же должно быть:

```js
const hasAdvantage = hasHeavyArmor || hasResistance;
```

Сейчас исправлю.

**Comment by bespoyasov** [comment]
Спасибо!
