### ISSUE TITLE
Глава 11. Сайд эффекты. Неизменяемость по умолчанию. Терминология "изменение массива"

### ISSUE THREAD

**Issue by VictorDanilov** [bespoyasov/refactor-like-a-superhero#54]
Привет. Возможно ерунда и не стоит капать вглубь, поэтому смотри сам, стоит ли править, но просто опишу свои мысли.

[Неизменяемость по умолчанию](https://github.com/bespoyasov/refactor-like-a-superhero/blob/main/manuscript-ru/11-side-effects.md#%D0%BD%D0%B5%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D1%8F%D0%B5%D0%BC%D0%BE%D1%81%D1%82%D1%8C-%D0%BF%D0%BE-%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E)

> Действия внутри функции меняют массив items

Вот тут смотря что имеется ввиду под "изменениями массива". Для меня это добавление, удаление или замена элемента. Тут же мы получили массив ссылок на объекты, и вернули этот же массив с этими же ссылками на объекты. Ничего по сути не изменилось. Замутировали как раз объекты. Поэтому фраза `Действия внутри функции меняют массив items` читается как-то странно. Да, в целом, понятно из примера что имеется ввиду, но могут найтись люди, которым этот момент тоже может показаться странным. Да и то, что тут подымается тема мутации, работе по ссылке вроде как заставляет более аккуратно относиться к словам про изменения. Поэтому меня так зацепила эта фраза "меняют массив". Сам пример и цепочка рассуждений хорошая. Вот, думал, может чуть-чуть как-то слова про изменение массива вначале подобрать, чтобы было технически "правильнее" что ли, а не поверхностно-человечески, в духе "ну да, в целом обычный человек может сказать что массив поменялся, раз поменялось что-то в одном из контейнеров, что этот массив хранил":)

Просто мысли:) Возможно это всё и не нужно, поэтому через ишью, а не ПР:)

**Comment by bespoyasov** [comment]
Я немного подправил вводный параграф, чтобы было яснее, что имеется в виду на протяжении раздела. Спасибо!
