### ISSUE TITLE
Глава 11. Сайд эффекты. Сценарии тестирования readLogEntry

### ISSUE THREAD

**Issue by VictorDanilov** [bespoyasov/refactor-like-a-superhero#55]
[Команды и запросы](https://github.com/bespoyasov/refactor-like-a-superhero/blob/main/manuscript-ru/11-side-effects.md#%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B-%D0%B8-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D1%8B)

```
// readLogEntry.test.ts

describe("when given an ID", () => {
  it("should call the logger service with that ID", () => {
    const spy = jest.spyOn(logger, "getById");
    readLogEntry("test-entry-id");
    expect(spy).toHaveBeenCalledWith("test-entry-id");
  });
});

// createLogEntry.test.ts

describe("when given an ID", () => {
  it("should call the logger service create with that ID and default entry data", () => {
    const spy = jest.spyOn(logger, "createEntry");
    createLogEntry("test-entry-id");
    expect(spy).toHaveBeenCalledWith("test-entry-id", timeStub, "Access");
  });
});
```

С тестом `createLogEntry `ок, тестируем видимое поведение - вызов (эффект). Со сценарием вызова лога в `readLogEntry ` тоже ок. Но что с другими сценариями? Да, чтобы не раздувать всеми тестами текст, вроде можно опустить. Но выше мы вводили читателя в тестирование возвращаемого результата. А сейчас как будто лишили его этих проверок, показав важность лишь проверки вызова. Но тут такие моменты. Если мы из `readLogEntry` уберем `return`, то тест пройдет. Мы можем написать тест на сценарий возврата `null `без мока логгера. Но сценарий ветки, где возврат значения после отработки логгера ведь тоже важен? Вдруг код изменят так, что вызов лога останется, но возврат потеряется. И такое без мока `logger.getById` не сделать? То есть, от моков мы в этом сценарии не уйдем? Или я чего-то не понял:)

**Comment by bespoyasov** [comment]
> То есть, от моков мы в этом сценарии не уйдем?

Тут цель была не в том, чтобы полностью уйти от моков, а скорее чтобы разделить слабо связанные задачи (создание / чтение) и уйти от неожиданных эффектов.

> Выше мы вводили читателя в тестирование возвращаемого результата. 

Да, потому что функция `getOrCreateLogEntry` не гарантировала идемпотентного чтения из логгера. 

После изменения `readLogEntry` читает всегда одинаковую запись из лога, если ей передали тот же ID, поэтому дополнительный тест на сравнение записей будет лишь проверять работу мока:

```ts
it("should return the correct log entry", () => {
  jest.spyOn(logger, "getById").mockImplementation(() => testEntry);
  const result = readLogEntry("test-entry-id");
  
  // Что передали, то и проверили:
  expect(result).toEqual(testEntry); 
});
```

Иногда подобные «адаптеры» могутещё как-то подстраивать интерфейс под нужды приложения. (Случай, когда тело функции как-то меняет, обновляет или обогащает прочитанную запись, это как раз оно.) Тогда будет иметь смысл проверить, что возвращаемый результат соответствует этому интерфейсу, но об этом я упомянул во врезке дальше:

<img width="644" alt="«Screenshot» 2023-02-06 at 09 02 29" src="https://user-images.githubusercontent.com/9102374/216916996-d33511a5-85d1-4db3-a73d-461071c7819d.png">

То есть вполне можно перестраховаться и написать тест по типу того, что выше, но я в этом смысла не увидел. Могу ошибаться, если есть контр-примеры, можем обсудить.

> Вдруг код изменят так, что вызов лога останется, но возврат потеряется.

А эту проблему, на мой взгляд, должна решать статическая типизация.

Всегда есть вариант, что не будут проставлены типы на самой функции, но там, где мы её используем, скорее всего, мы ожидаем результат вместо `void`, поэтому TS должен подсветить эту проблему.

**Comment by VictorDanilov** [comment]
> А эту проблему, на мой взгляд, должна решать статическая типизация.

Точно, спасибо:)

В целом понял, можно ишью закрывать тогда.
