### ISSUE TITLE
Глава 12. Обработка ошибок. Проблемы выбрасывания. Сигнатура функции

### ISSUE THREAD

**Issue by VictorDanilov** [bespoyasov/refactor-like-a-superhero#57]
[Проблемы](https://github.com/bespoyasov/refactor-like-a-superhero/blob/main/manuscript-ru/12-error-handling.md#%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B)

> Сигнатура функций не сообщает, что они могут выбросить ошибку — мы можем узнать об ошибках только из исходников.

Тут я сразу подумал о типе `never`. Вроде мы можем этим намекнуть, что в коде может быть брошена ошибка. Да, мы не понимаем, что именно это за ошибка через типы как у тебя ниже, `FetchUserError `или `ParseUserError`. Но в контексте фразы, читается так, что never чисто технически, но грубо, может намекнуть на наличие выбрасывания через сигнатуру. Может быть это стоит упомянуть как-то.

**Comment by bespoyasov** [comment]
Да, это можно попробовать оформить в виде дополнения в скобках прямо в списке или, если оно будет слишком длинное, в виде врезки сразу после списка. (Во втором случае, вероятно, будет полезно подвинуть пункт о сигнатурах в конец списка, чтобы при переходе во врезку контекст не терялся.)

Я бы только упомянул, что чтобы понять, какую именно ошибку выбрасывает функция, всё равно придётся лезть в исходники. Просто чтоб не создавалось впечатления, будто проблема полностью решается с помощью `never` 😃 

Попробуешь взять?

**Comment by VictorDanilov** [comment]
Открыл ПР. Если что-то по тексту не так или есть ошибки в английском, поправь плиз:)

**Comment by bespoyasov** [comment]
Спасибо! Гляну на неделе 🚀
