### ISSUE TITLE
Добавить к рефакторингу Фаулера версию книгу с примерами на JS

### ISSUE THREAD

**Issue by Seminioni** [bespoyasov/refactor-like-a-superhero#61]
Может быть стоит добавить в дополнение к “Refactoring” by Martin Fowler, Kent Beck, https://www.goodreads.com/book/show/44936.Refactoring ту же книгу на русском языке? https://www.ozon.ru/product/refaktoring-koda-na-javascript-uluchshenie-proekta-sushchestvuyushchego-koda-156082567/?sh=tx6m_osG8g

**Comment by bespoyasov** [comment]
О, конкретно эту книгу я как-то пропустил. Думаю, мне стоит её сперва прочесть, чтобы добавить в референсы. Положил себе в список для чтения, спасибо! :–)

**Comment by Seminioni** [comment]
> 



> О, конкретно эту книгу я как-то пропустил. Думаю, мне стоит её сперва прочесть, чтобы добавить в референсы. Положил себе в список для чтения, спасибо! :–)

А ты что читал все книги из списка литературы? :)

**Comment by bespoyasov** [comment]
Да, всё, что лежит в референсах к этой книге, прочитано и посмотрено, иначе бы не было смысла ссылаться на них. 

Другое дело, что мне, вероятно, некоторые материалы стоит перечитать, потому что читал я их давно и сейчас мнение или понимание может поменяться. Но в списке я, по крайней мере, ссылаюсь на вещи, которые помню или записывал.

P.S. В прошлый раз, кстати, когда мне указали на хорошую книжку, я её [добавил после того, как прочёл](https://github.com/bespoyasov/refactor-like-a-superhero/pull/25). Это может занять какое-то время 😃
