### ISSUE TITLE
Глава 13. Интеграция модулей ошибок. Зависимости.

### ISSUE THREAD

**Issue by Voyager101pw** [bespoyasov/refactor-like-a-superhero#67]
[Источник](https://github.com/bespoyasov/refactor-like-a-superhero/blame/17353ba54623ce39af29831da4e016e01ec9ce83/manuscript-ru/13-module-integration.md#L382)
> Говоря о зацеплении и интеграции модулей, стоит упомянуть управление зависимостями. `Под зависимостями для простоты будем иметь в виду любой код, который используется нашим`. Например, в функции randomInt кроме двух аргументов мы используем метод Math.random — это зависимость:

Предложение кажется не законченным, возможно стоит что-то добавить?

**Comment by bespoyasov** [comment]
Привет!

Вообще, изначально мне казалось, что предложение вполне закончено. Оценивая сейчас свежим взглядом, возможно, действительно стоит дописать в конце «кодом»:

> Под зависимостями для простоты будем иметь в виду любой код, который используется нашим кодом.

Насколько будет лучше звучать?

**Comment by Voyager101pw** [comment]
Звучит здорово!
