### ISSUE TITLE
Suggestion about structural typing

### ISSUE THREAD

**Issue by VictorDanilov** [bespoyasov/refactor-like-a-superhero#7]
Когда читал [Типы для описания домена](https://github.com/bespoyasov/refactor-like-a-superhero-online-book/blob/main/manuscript-ru/06-names.md#%D1%82%D0%B8%D0%BF%D1%8B-%D0%B4%D0%BB%D1%8F-%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD%D0%B0) возникли мысли о структурной типизации, потому что обычно читая примеры кода, где статическая типизация во фронте, думаешь сразу о Typescript. Из-за этого перед врезкой "Подробнее", напрашивается еще одна врезка, например, "К слову", где можно упомянуть о структурной типизации, и что из-за неё у нас не будет 100% защиты от использования "неправильного" типа по смысловому неймингу домена, как в случае с номинативной.

Были ли такие мысли и опустил это намеренно, чтобы не перегружать текст? Что думаешь?

В целом, по тексту всей книги не нашел упоминания структурной типизации. Может быть стоит где-то сделать про это вброс в контексте рефакторинга или чего-то ещё, только пока не знаю, что предложить, так как дальше книгу не читал ещё.

**Comment by bespoyasov** [comment]
Это хорошее замечание, да.

Я в целом старался при написании держать в голове помимо TS другие языки тоже, поэтому в главах, не связанных напрямую с типизацией редко упоминал именно его особенности. Но при этом, думаю, упомянуть структурную типизацию может быть полезно в секции о [Типизации в TypeScript](https://github.com/bespoyasov/refactor-like-a-superhero-online-book/blob/main/manuscript-ru/17-static-typing.md#типизация-в-typescript). 

Судя по всему, удобнее будет добавить врезку в эту главу, но я пока не могу понять, куда лучше её добавить 😃 

Пока выбираю между двумя вариантами:
- добавить в раздел «Типизация в TypeScript» ближе к концу — как пример, как алиасы могут быть ненадёжными;
- добавить во врезку «Перед началом» в начале главы — как предостережение перед прочтением, что в других языках могут быть отличия.

Какие у тебя идеи об этом? Может, есть другие варианты тоже? (Как вариант, можем отложить до момента, когда получится дочитать до главы о типизации.)

**Comment by bespoyasov** [comment]
Кажется, у меня получилось внедрить упоминание структурной и номинативной типизации прямо в текст 😃 

Создал PR. Посмотри, пожалуйста? 
Как думаешь, стоит ли улучшить какие-то формулировки ещё?

**Comment by VictorDanilov** [comment]
Угу, смотрится хорошо, отсылка есть. Текст про тайп-алиасы теперь более четко показывает, что может привести к невалидной доменной модели. Но я вот думаю, стоит ли в саму главу добавлять дополнительные пример, где прям структурная типизация раскрывается, или достаточно того, что мы направили читателя в доку тайпскрипта, где он сам сделает выводы, как структурная типизация может повлиять на выстраивание и работу с типами домена. Просто тайп-алиасы не очень ведь завязаны на структурную типизацию в примере кода в главе. Мы лишь поигрались с примитивом number. И как будто хочется ниже еще одного примера уже с объектами какими-то.

**Comment by bespoyasov** [comment]
Мне кажется, ссылки на документацию достаточно, так как и понятие самих тайп-алиасов мы тоже не особо раскрываем 🤔 

Я боюсь, что если мы будем описывать в деталях все тонкости системы типов TS, то суть главы сильно размоется, а количество текста неоправданно вырастет. Хочется баланса между количеством переданного и фокусом на использовании типизации как инструмента для рефакторинга и проектирования.

> Просто тайп-алиасы не очень ведь завязаны на структурную типизацию в примере кода в главе. Мы лишь поигрались с примитивом number. И как будто хочется ниже еще одного примера уже с объектами какими-то.

Да, тут ты прав.

Я там докинул один комит, в котором добавил врезку с предупреждением, что мы фокусируемся не на деталях типизации. Заодно разрубил логический переход от структурной типизации к примеру с алиасом. Сейчас пример больше относится к параграфу с мыслью о сложности в передаче ограничений, чем к параграфу о структурной типизации как таковой.

Вероятно, добавить более скромную врезку подходит больше, чем пытаться встроить понятие прямо в текст. Просто чтобы мысль в сторону не уводило. Насколько сейчас текст выглядит стройно?

P.S. Большое спасибо за помощь при вычитке! Это полезно :—)

**Comment by VictorDanilov** [comment]
> Я боюсь, что если мы будем описывать в деталях все тонкости системы типов TS, то суть главы сильно размоется, а количество текста неоправданно вырастет. Хочется баланса между количеством переданного и фокусом на использовании типизации как инструмента для рефакторинга и проектирования.

Да, полностью согласен, поэтому сверху побеспокоился, что можем перегрузить текст лишним.

Новая врезка прям хорошо намекает и направляет. Найс:)

У меня в закладках есть такая [ссылка про типизации на русском](https://typescript-definitive-guide.ru/book/chapters/Sovmestimost_tipov_na_osnove_vida_tipizacii/) еще. Обычно своим студентам на курсах даю там читать про это. Если тебе понравится как там, её тоже можно добавить.

> P.S. Большое спасибо за помощь при вычитке! Это полезно :—)

Ооо, такой клевый материал хочется вычитывать и дополнять:) Грамотное вплетение обоснований, отсылки всякие. Редко что-то на таком уровне встречал в ру сегменте, где не просто материал, а куча ещё всякого фундаментального вбрасывается. Это как у [khalilstemmler](https://khalilstemmler.com/). Как заходишь к нему в какую-нибудь статью, а там отсылка на отсылке к каким-нибудь фундаментальным вещах. Очень круто, что у тебя получается собирать такое в единое целое для ру сегмента, и читается хорошо и легко. Прям смело можно рекомендовать людям тебя читать, когда просят совета, как фундамент знаний построить:)

Давай мержиться тогда, вроде всё ок:)

**Comment by bespoyasov** [comment]
> Новая врезка прям хорошо намекает и направляет. Найс:)

Отлично!

> У меня в закладках есть такая ссылка про типизации на русском еще. Обычно своим студентам на курсах даю там читать про это. Если тебе понравится как там, её тоже можно добавить.

Ага, TDG — отличный ресурс, да. Добавил 👍 

> Это как у khalilstemmler.

Я, кстати, на него в нескольких главах тоже ссылаюсь 😅 

> Очень круто, что у тебя получается собирать такое в единое целое для ру сегмента, и читается хорошо и легко. Прям смело можно рекомендовать людям тебя читать, когда просят совета, как фундамент знаний построить:)

Рад, что полезно! 
И спасибо ещё раз за помощь!
