### ISSUE TITLE
Website source?

### ISSUE THREAD

**Issue by gurugeek** [bespoyasov/refactor-like-a-superhero#71]
First of all, thanks a lot for your book :) I was wondering if it is possible to share the website source: https://refactoring-book.vercel.app/en.
I read that it was developed with Svelte, but I need help finding the source—many thanks for considering my request.
David

**Comment by bespoyasov** [comment]
Hey!
Thanks, glad you found it helpful!

The source code is in a closed repo, and I haven't had plans to make it public yet. But if you wanted to take a look not at this specific code base but just at an example of SvelteKit-based code in general, I can offer my [blog's source](https://github.com/bespoyasov/www), which is also built with SvelteKit.

Hope that helps!

**Comment by gurugeek** [comment]
@bespoyasov, thank you very much for your prompt and kind reply. I looked at the blog source (in fact, I checked all your repositories as I thought I was missing something!). I completely understand. I have used Sveltekit in the past for small projects. Ultimately, I used NextJS for the book site as there are many more templates for fast prototyping. Thanks again, and all the best for the new year!

**Comment by bespoyasov** [comment]
No worries, and happy new year to you too!
