### ISSUE TITLE
15 - Архитектура

### ISSUE THREAD

**Issue by BulatSa** [bespoyasov/refactor-like-a-superhero#72]
Опечатка в примере кода. Как я понимаю, должно быть `auction.participants.filter(ownsLot)`

```
// При выводе участников, которые победили по лотам:
function defineWinners(auction) {
  return { ...auction, winners: participants.filter(ownsLot) };
}
```

Ниже, пропущен предлог `в`

`Обычно его стоит добавлять места, где есть`

**Comment by bespoyasov** [comment]
Спасибо за внимательность!
